### PR TITLE
Added instructions of installing the API using nuget.org

### PR DESCRIPTION
**Pull request by ghost**
The Solace Messaging API for C#/.NET (also referred to as SolClient for .NET) is going to be available through nuget.org.

This change has instructions of installing the API using nuget.org for all currently available C# tutorials.

Signed-off-by: Dmitri Fedorov <dfedorov.solace@gmail.com>

### CODE REVIEW

**Comment by mdspielman** [comment]
Could you raise a GitHub issue to track your suggestion of using Nuget.org. It'll be important to understand the timing of when the API is available in nuget to coordinate the merge.

**Comment by dfedorov-solace** [comment]
This is originated from an internal defect report in Bugzilla, it's not my suggestion :-)

**Comment by ghost** [comment]
Opened issue #11

**Comment by mdspielman** [comment]
Please see request in issue #11. Please add readme updates as well to the pull request.

**Pull request closed without merging**
